"""add datetime column for contract

Revision ID: 2b1f848e0c29
Revises: 571bce9115d8
Create Date: 2024-11-18 23:35:39.962407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1f848e0c29'
down_revision: Union[str, None] = '571bce9115d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('signed_datetime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'signed_datetime')
    # ### end Alembic commands ###
