"""timestamp to Feedback

Revision ID: 69ea4de712dc
Revises: e74eaa15ddbe
Create Date: 2024-11-19 00:13:30.225106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ea4de712dc'
down_revision: Union[str, None] = 'e74eaa15ddbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback', 'timestamp')
    # ### end Alembic commands ###
